---
title: "Correlation between differentiall expression changes in bulk and single cell datasets"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/home/tema/work/skolkovo/fish_project/")
knitr::opts_chunk$set(echo=FALSE, message = FALSE)
```

```{r, results = 'hide'}
library(ggplot2)
library(dplyr)
library(Seurat)
```


```{r prepping_sc_DEGs}
# Loading DEGs generated by Seurat for the whole dataset saline vs freshwater
sc_DEGs <- read.csv(file = "data/DEGs.by.salinity.all.csv", header = TRUE)
id_match_table <- read.table(file = "data/10X_features.tsv", header = FALSE, sep = "\t", col.names = c("ensembl", "mixed", "type"))[,1:2]
sc_DEGs <- merge(sc_DEGs, id_match_table, by.x = "X", by.y = "mixed")
rownames(sc_DEGs) <- sc_DEGs$ensembl

sc_DEGs_filtered <- subset(sc_DEGs, abs(avg_logFC) > 0.25)
```

```{r calculation_bulk_DEGs}
bulk_DEGs <- as.data.frame(readxl::read_xlsx("data/S5C_table_RNAseq_DEG_MMFF.xlsx"))
rownames(bulk_DEGs) <- bulk_DEGs$...1
bulk_DEGs_common <- bulk_DEGs[sc_DEGs$ensembl, ]

bulk_DEGs_common_filtered <- bulk_DEGs[sc_DEGs_filtered$ensembl, ]
```

```{r plotting_corr_bulk_vs_sc}
require(ggpubr)
#combining DEG tables
combined_DEGs <- merge(sc_DEGs[,c("avg_logFC", "p_val", "ensembl")], bulk_DEGs_common[,c("logFC", "PValue", "...1")], by.x = "ensembl", by.y = "...1")
colnames(combined_DEGs) <- c("ensembl", "single_cell_logFC", "single_cell_pval", "bulk_logFC", "bulk_pval")
rownames(combined_DEGs) <- combined_DEGs$ensembl
write.table(combined_DEGs, file = "data/DEGs_overlapping_sc_and_bulk.tsv", sep = "\t")

ggscatter(combined_DEGs,
      x = "single_cell_logFC", y = "bulk_logFC", size = 1.5) +
      theme_gray() +
      stat_cor(method = "pearson", label.x = -5, label.y = 5, size=3, color="#696969")+
      coord_cartesian(xlim = c(-5, 5), ylim = c(-5, 5)) +
      labs(title = "Corelation scatter plot single cell DEGs vs bulk")
```

```{r}
cor.test(combined_DEGs$single_cell_logFC, combined_DEGs$bulk_logFC, method = "pearson")
cor.test(combined_DEGs$single_cell_logFC, combined_DEGs$bulk_logFC, method = "spearman")
```

```{r plotting_corr_bulk_vs_filtered_sc}
require(ggpubr)
#combining DEG tables
combined_DEGs <- merge(sc_DEGs_filtered[,c("avg_logFC", "ensembl")], bulk_DEGs_common_filtered[,c("logFC", "...1")], by.x = "ensembl", by.y = "...1")
colnames(combined_DEGs) <- c("ensembl", "single_cell_logFC", "bulk_logFC")
rownames(combined_DEGs) <- combined_DEGs$ensembl

ggscatter(combined_DEGs,
      x = "single_cell_logFC", y = "bulk_logFC", size = 1.5) +
      theme_gray() +
      stat_cor(method = "pearson", label.x = -5, label.y = 5, size=3, color="#696969")+
      coord_cartesian(xlim = c(-5, 5), ylim = c(-5, 5)) +
      labs(title = "Corelation scatter plot single cell DEGs (filtered logFC > 0.25) vs bulk")
```
