---
title: "Testing significance of the shift in distance histograms"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/home/tema/work/skolkovo/fish_project/")
knitr::opts_chunk$set(echo=FALSE, message = FALSE)
```

```{r, results = 'hide'}
library(ggplot2)
library(dplyr)
library(Seurat)
```

```{r separating_blood_cluster}
load(file = "data/rna.integrated.filtered.after.clustering.obj.RData")
rna.integrated.cluster.blood <- subset(rna.integrated, idents = 0)
rna.integrated.cluster.rest <- subset(rna.integrated, idents = c(1,2))
# save(rna.integrated.cluster.blood, file = "data/rna.integrated.cluster.blood.RData")
# save(rna.integrated.cluster.rest, file = "data/rna.integrated.cluster.rest.RData")
```

### PCA plot of the blood cluster by the samples

```{r blood_cluster_PCA_plot}
rna.integrated.cluster.blood <- FindNeighbors(rna.integrated.cluster.blood, dims = 1:15)
rna.integrated.cluster.blood  <- FindClusters(rna.integrated.cluster.blood, resolution = 0.3)
rna.integrated.cluster.blood <- RunPCA(rna.integrated.cluster.blood)
DimPlot(rna.integrated.cluster.blood, reduction = "pca", group.by = "orig.ident")
```

```{r calculate_distances_from_pca_blood_cluster}
set.seed(42)
pca_raw_blood <- as.data.frame(rna.integrated.cluster.blood@reductions[["pca"]]@cell.embeddings)
pca_raw_blood$sample <- rna.integrated.cluster.blood@meta.data[["orig.ident"]]
pca_raw_blood <- pca_raw_blood[sample(nrow(pca_raw_blood)), c(1:10,51)]
pca_saline <- subset(pca_raw_blood, sample %in% c("stickleback.sample.1", "stickleback.sample.2"))[,1:10]
pca_freshwater <- subset(pca_raw_blood, sample %in% c("stickleback.sample.3", "stickleback.sample.4"))[,1:10]

pca_saline_1_half <- pca_saline[1:4672,]
pca_saline_2_half <- pca_saline[4674:nrow(pca_saline),]
colnames(pca_saline_2_half) <- paste(colnames(pca_saline_2_half), ".2half", sep="")
# pca_salineVsaline <- cbind(pca_saline_1_half, pca_saline_2_half)
dist_matrix_salineVsaline <- fields::rdist(pca_saline_1_half, pca_saline_2_half)

dist_matrix_salineVfreshwater <- fields::rdist(pca_saline, pca_freshwater[1:nrow(pca_saline),])

pca_freshwater_1_half <- pca_freshwater[1:4907,]
pca_freshwater_2_half <- pca_freshwater[4909:nrow(pca_freshwater),]
colnames(pca_freshwater_2_half) <- paste(colnames(pca_freshwater_2_half), ".2half", sep="")
# pca_freshwaterVfreshwater <- cbind(pca_freshwater_1_half, pca_freshwater_2_half)
dist_matrix_freshwaterVfreshwater <- fields::rdist(pca_freshwater_1_half, pca_freshwater_2_half)


# dist_salineVsaline <- apply(pca_salineVsaline, Eucle)
```

### Histograms of pairwise distance saline/freshwater

```{r parwise_histrograms_of_distances_between_diff_water_types}
frame_for_hist <- data.frame(dist = c(as.vector(dist_matrix_salineVsaline), as.vector(dist_matrix_salineVfreshwater), as.vector(dist_matrix_freshwaterVfreshwater)),
                             pair = c(rep("salineVsaline", length(dist_matrix_salineVsaline)),
                                      rep("salineVfreshwater", length(dist_matrix_salineVfreshwater)),
                                      rep("freshwaterVfreshwater", length(dist_matrix_freshwaterVfreshwater))))

mu <- plyr::ddply(frame_for_hist, "pair", summarise, grp.mean=mean(dist))

small_frame_for_hist <- frame_for_hist[sample(nrow(frame_for_hist), 100000),]

p <- ggplot(small_frame_for_hist, aes(x=dist, fill=pair, color=pair)) +
  geom_histogram(position="identity", alpha=0.5, binwidth = 0.25) + 
  geom_vline(data=mu, aes(xintercept=grp.mean, color=pair),
             linetype="dashed")
p
```


### Normality test

```{r test_dist_hist_for_blood_shift_mann_whitney}
# shapiro.test(dist_hist_small_sVf$dist[1:4900])
small_frame_for_hist_casted <- small_frame_for_hist
# small_frame_for_hist_casted$ID <- rownames(small_frame_for_hist_casted)
salineVsaline_vec <- subset(small_frame_for_hist, pair == "salineVsaline")$dist
freshwaterVfreshwate_vec <- subset(small_frame_for_hist, pair == "freshwaterVfreshwater")$dist
wilcox.test(salineVsaline_vec,freshwaterVfreshwate_vec)
ks.test(freshwaterVfreshwate_vec,salineVsaline_vec)
```


```{r}

```





